# Generated by Django 5.0.7 on 2024-08-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_titlte_task_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
